### ISSUE TITLE
sysfiles undefined

### ISSUE THREAD

**Issue by rveltz** [SimonDanisch/PackageCompiler.jl#1]
Hi,

I am trying your Makie precompile solution and I have some troubles. Basically

```julia
using PackageCompiler; PackageCompiler.revert()
ERROR: UndefVarError: sysfiles not defined
Stacktrace:
 [1] revert(::Bool) at /Users/rveltz/.julia/v0.6/PackageCompiler/src/PackageCompiler.jl:62
 [2] revert() at /Users/rveltz/.julia/v0.6/PackageCompiler/src/PackageCompiler.jl:59
```

I looked at your code and it seems `sysfiles` is undefined...

Maybe there is a quick fix...

Best regards

**Comment by SimonDanisch** [comment]
Thanks for trying this out and reporting it :) I wish I could just have more thorough tests, but it's a bit hard especially when you consider that build times are around ~20 min.
