### ISSUE TITLE
Failed to compile PyCall

### ISSUE THREAD

**Issue by TsurHerman** [SimonDanisch/PackageCompiler.jl#11]
Actually the failure is something else, but trying to compile PyCall is the MWE

output is 
```
/Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/base/precompile.jl
LoadError("sysimg.jl", 411, LoadError("/Applications/Julia-0.6.app/Contents/Resources/julia/share/julia/base/userimg.jl", 3, LoadError("/Users/tsurherman/.julia/v0.6/PyCall/src/PyCall.jl", 28, LoadError("/Users/tsurherman/.julia/v0.6/Conda/src/Conda.jl", 309, LoadError("/Users/tsurherman/.julia/v0.6/Conda/src/bindeps_conda.jl", 2, LoadError("/Users/tsurherman/.julia/v0.6/BinDeps/src/BinDeps.jl", 10, UndefVarError(:JULIA_HOME)))))))
```

What do you make of it?

**Comment by SimonDanisch** [comment]
Seems Like BinDeps is using JULIA_HOME, which doesn't seem to be available in this early stage of system image compilation. 
But this looks like you're precompiling parts of the build process?

**Comment by TsurHerman** [comment]
Yep, it relates to the way BinDeps is being precomiled. 

By the way in Julia 0.7 JULIA_HOME is replaced with Sys.BINDIR which is defined so this problem goes away.

By the way, 
The force=true option is broken though on Mac and on windows , I had to sort it out manually

**Comment by SimonDanisch** [comment]
See: https://github.com/SimonDanisch/PackageCompiler.jl/issues/12

**Comment by SimonDanisch** [comment]
Does this work on 0.7?

I will close this issue, since it's more about getting a certain package to precompile!

**Comment by TsurHerman** [comment]
I don't know .. we are still on 0.6, and tight on schedule so ...
The manual thing I did was just copying the sys.dll/dylib/so to Julia lib dir , while renaming the current sys.dll sys.dll.bak

seems good enough
